''' Regular Playing Cards Deck '''

from cards import *

PCDeckHearts = Deck()
PCDeckDiamonds = Deck()
PCDeckClubs = Deck()
PCDeckSpades = Deck()

PCDeckHearts += Card("Ace of Hearts",1)
PCDeckHearts += Card("Two of Hearts",2)
PCDeckHearts += Card("Three of Hearts",3)
PCDeckHearts += Card("Four of Hearts",4)
PCDeckHearts += Card("Five of Hearts",5)
PCDeckHearts += Card("Six of Hearts",6)
PCDeckHearts += Card("Seven of Hearts",7)
PCDeckHearts += Card("Eight of Hearts",8)
PCDeckHearts += Card("Nine of Hearts",9)
PCDeckHearts += Card("Ten of Hearts",10)
PCDeckHearts += Card("Jack of Hearts",11)
PCDeckHearts += Card("Queen of Hearts",12)
PCDeckHearts += Card("King of Hearts",13)

PCDeckDiamonds += Card("Ace of Diamonds",1)
PCDeckDiamonds += Card("Two of Diamonds",2)
PCDeckDiamonds += Card("Three of Diamonds",3)
PCDeckDiamonds += Card("Four of Diamonds",4)
PCDeckDiamonds += Card("Five of Diamonds",5)
PCDeckDiamonds += Card("Six of Diamonds",6)
PCDeckDiamonds += Card("Seven of Diamonds",7)
PCDeckDiamonds += Card("Eight of Diamonds",8)
PCDeckDiamonds += Card("Nine of Diamonds",9)
PCDeckDiamonds += Card("Ten of Diamonds",10)
PCDeckDiamonds += Card("Jack of Diamonds",11)
PCDeckDiamonds += Card("Queen of Diamonds",12)
PCDeckDiamonds += Card("King of Diamonds",13)

PCDeckClubs += Card("Ace of Clubs",1)
PCDeckClubs += Card("Two of Clubs",2)
PCDeckClubs += Card("Three of Clubs",3)
PCDeckClubs += Card("Four of Clubs",4)
PCDeckClubs += Card("Five of Clubs",5)
PCDeckClubs += Card("Six of Clubs",6)
PCDeckClubs += Card("Seven of Clubs",7)
PCDeckClubs += Card("Eight of Clubs",8)
PCDeckClubs += Card("Nine of Clubs",9)
PCDeckClubs += Card("Ten of Clubs",10)
PCDeckClubs += Card("Jack of Clubs",11)
PCDeckClubs += Card("Queen of Clubs",12)
PCDeckClubs += Card("King of Clubs",13)

PCDeckSpades += Card("Ace of Spades",1)
PCDeckSpades += Card("Two of Spades",2)
PCDeckSpades += Card("Three of Spades",3)
PCDeckSpades += Card("Four of Spades",4)
PCDeckSpades += Card("Five of Spades",5)
PCDeckSpades += Card("Six of Spades",6)
PCDeckSpades += Card("Seven of Spades",7)
PCDeckSpades += Card("Eight of Spades",8)
PCDeckSpades += Card("Nine of Spades",9)
PCDeckSpades += Card("Ten of Spades",10)
PCDeckSpades += Card("Jack of Spades",11)
PCDeckSpades += Card("Queen of Spades",12)
PCDeckSpades += Card("King of Spades",13)
